#!/usr/bin/env python

import json
import urllib2
import argparse
import sys
import os

import git

def get_tutorial_dir(tutorial):
    """
    Find first unused tutorial directory
    """
    trial_dir = os.path.join(".", tutorial)
    if not os.path.exists(trial_dir):
        return trial_dir
    postfix = 1
    while True:
       test_dir = "%s.%d" % (trial_dir, postfix)
       if not os.path.exists(test_dir):
           return test_dir
       postfix += 1

def get_tutorials():
    """
    Use github api to get a list of tutorials currently available
    """
    github_page = urllib2.urlopen("https://api.github.com/orgs/osgconnect/repos")
    repo_data = json.load(github_page)
    repos = [ (x['name'], x['description'], x['git_url']) for x in repo_data ]
    tutorial_repos = {}
    for repo in repos:
        if repo[0].startswith('tutorial-'):
            tutorial_repos[repo[0]] = {'description': repo[1],
                                       'url' : repo[2]}
    return tutorial_repos

def main():
    """
    Run script and try to get and install correct tutorial files
    """

    parser = argparse.ArgumentParser(description='Install tutorial files.')
    parser.add_argument('--list', dest='list', action='store_true',
                        default=False, help='List available tutorials')
    parser.add_argument('--info', dest='info', 
                        default=None, nargs=1, help='Print info on specified tutorial')
    parser.add_argument('--install', dest='install', 
                        default=None, nargs=1, help='Install files for specified tutorial')
    txt = "should be either list, info, or tutorial name to list available tutorials," \
          "get info on a specified tutorial, or install the specified tutorial respectively"
    parser.add_argument('cmd', nargs='*', help=txt, default=None)
    args = parser.parse_args(sys.argv[1:])
    # list tutorials
    if (args.cmd != [] and args.cmd[0] == 'list') or args.list:
        tutorials = get_tutorials()
        sys.stdout.write("Currently available tutorials: \n")
        for tutorial in tutorials:
            description = tutorials[tutorial]['description']
            sys.stdout.write("%s - %s\n" % (tutorial, description))
        sys.exit(0)
    # provide info on a given tutorial
    elif (args.cmd != [] and args.cmd[0] == 'info') or args.info:
        tutorials = get_tutorials()
        if len(args.cmd) > 1:
            tutorial = args.cmd[1]
        else:
            tutorial = args.info[0]
        if tutorial not in tutorials:
            sys.stderr.write("Tutorial %s not found, available tutorials "
                             "are:\n" % tutorial)
            for key in tutorials:
                sys.stderr.write("%s\n" % key)
            sys.exit(1)
        else:
            sys.stdout.write("%s - %s\n" % (tutorial, 
                                            tutorials[tutorial]['description']))
            sys.exit(0)
    # install tutorial
    elif (args.cmd != []) or args.install:
        if args.cmd != []:
            tutorial = args.cmd[0] 
        elif args.install != []:
            tutorial = args.install[0]
        tutorials = get_tutorials()
        if tutorial not in tutorials:
            sys.stderr.write("Tutorial %s not found, available tutorials "
                             "are:\n" % tutorial)
            for key in tutorials:
                sys.stderr.write("%s\n" % key)
            sys.exit(1)
        tutorial_dir = get_tutorial_dir(tutorial)
        if os.path.exists(os.path.join(".", tutorial)):
            sys.stdout.write("Directory %s exists, putting tutorial files "\
                             "in %s\n" % (tutorial, tutorial_dir))
        git.Repo.clone_from(tutorials[tutorial]['url'], tutorial_dir)
        sys.stdout.write("Tutorial files installed in %s\n" % tutorial_dir)
    else:
        parser.print_help()
        sys.exit(1)
        
if __name__ == '__main__':
    main()
